version: '3'

services:
  service:
    build:
      context: .
    networks:
      - my_network
    depends_on:
      - postgres
    environment:
      RDS_HOST: postgresql://root:password@postgres
    stdin_open: true
    tty: true
    entrypoint: /bin/sh

  postgres:
    image: postgres:9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: root
      # POSTGRES_PASSWORD: password
    networks:
      - my_network

volumes:
  postgres-data:
    driver: local

networks:
  my_network:
    driver: bridge
